use bevy::prelude::*;

/// Configuration data for celestial bodies
#[derive(Clone, Debug)]
pub struct PlanetConfig {
    pub name: &'static str,
    pub radius_km: f32,
    pub mass_kg: f64,
    pub color: Color,
    pub orbital_distance_au: f32,
    pub orbital_period_days: f32,
    pub rotation_period_hours: f32,
    pub axial_tilt_deg: f32,
    pub parent_entity: Option<&'static str>,
}

/// All planet and moon configurations
pub const PLANET_CONFIGS: &[PlanetConfig] = &[
    // Planets
    PlanetConfig {
        name: "Sun",
        radius_km: 696340.0,
        mass_kg: 1.9885e30,
        color: Color::srgb(1.0, 1.0, 0.9),
        orbital_distance_au: 0.0,
        orbital_period_days: 0.0,
        rotation_period_hours: 601.2,
        axial_tilt_deg: 7.25,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Mercury",
        radius_km: 2439.7,
        mass_kg: 3.3011e23,
        color: Color::srgb(0.45, 0.45, 0.42),
        orbital_distance_au: 0.387,
        orbital_period_days: 87.969,
        rotation_period_hours: 1407.504,
        axial_tilt_deg: 0.034,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Venus",
        radius_km: 6051.8,
        mass_kg: 4.8675e24,
        color: Color::srgb(0.95, 0.85, 0.65),
        orbital_distance_au: 0.723,
        orbital_period_days: 224.701,
        rotation_period_hours: -5832.6,
        axial_tilt_deg: 177.36,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Earth",
        radius_km: 6371.0,
        mass_kg: 5.97237e24,
        color: Color::srgb(0.25, 0.45, 0.85),
        orbital_distance_au: 1.000,
        orbital_period_days: 365.256,
        rotation_period_hours: 23.934,
        axial_tilt_deg: 23.439,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Mars",
        radius_km: 3389.5,
        mass_kg: 6.4171e23,
        color: Color::srgb(0.85, 0.35, 0.15),
        orbital_distance_au: 1.524,
        orbital_period_days: 686.980,
        rotation_period_hours: 24.623,
        axial_tilt_deg: 25.19,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Jupiter",
        radius_km: 69911.0,
        mass_kg: 1.8982e27,
        color: Color::srgb(0.85, 0.65, 0.45),
        orbital_distance_au: 5.204,
        orbital_period_days: 4332.667,
        rotation_period_hours: 9.925,
        axial_tilt_deg: 3.13,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Saturn",
        radius_km: 58232.0,
        mass_kg: 5.6834e26,
        color: Color::srgb(0.9, 0.8, 0.5),
        orbital_distance_au: 9.582,
        orbital_period_days: 10759.346,
        rotation_period_hours: 10.7,
        axial_tilt_deg: 26.73,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Uranus",
        radius_km: 25362.0,
        mass_kg: 8.6810e25,
        color: Color::srgb(0.6, 0.8, 0.9),
        orbital_distance_au: 19.201,
        orbital_period_days: 30688.992,
        rotation_period_hours: -17.24,
        axial_tilt_deg: 97.77,
        parent_entity: None,
    },
    PlanetConfig {
        name: "Neptune",
        radius_km: 24622.0,
        mass_kg: 1.02413e26,
        color: Color::srgb(0.3, 0.5, 0.9),
        orbital_distance_au: 30.047,
        orbital_period_days: 60194.189,
        rotation_period_hours: 16.11,
        axial_tilt_deg: 28.32,
        parent_entity: None,
    },

    // Moons
    PlanetConfig {
        name: "Moon",
        radius_km: 1737.4,
        mass_kg: 7.342e22,
        color: Color::srgb(0.75, 0.75, 0.78),
        orbital_distance_au: 0.002569,
        orbital_period_days: 27.3217,
        rotation_period_hours: 655.722,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Earth"),
    },
    PlanetConfig {
        name: "Phobos",
        radius_km: 11.1,
        mass_kg: 1.06e16,
        color: Color::srgb(0.4, 0.3, 0.2),
        orbital_distance_au: 0.000032,
        orbital_period_days: 0.32,
        rotation_period_hours: 7.68,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Mars"),
    },
    PlanetConfig {
        name: "Deimos",
        radius_km: 6.2,
        mass_kg: 1.48e15,
        color: Color::srgb(0.5, 0.4, 0.3),
        orbital_distance_au: 0.000156,
        orbital_period_days: 1.26,
        rotation_period_hours: 30.24,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Mars"),
    },
    PlanetConfig {
        name: "Io",
        radius_km: 1821.6,
        mass_kg: 8.93e22,
        color: Color::srgb(0.9, 0.8, 0.4),
        orbital_distance_au: 0.0028,
        orbital_period_days: 1.77,
        rotation_period_hours: 42.48,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Jupiter"),
    },
    PlanetConfig {
        name: "Europa",
        radius_km: 1560.8,
        mass_kg: 4.8e22,
        color: Color::srgb(0.8, 0.8, 0.9),
        orbital_distance_au: 0.0045,
        orbital_period_days: 3.55,
        rotation_period_hours: 85.2,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Jupiter"),
    },
    PlanetConfig {
        name: "Ganymede",
        radius_km: 2634.1,
        mass_kg: 1.48e23,
        color: Color::srgb(0.6, 0.6, 0.7),
        orbital_distance_au: 0.0072,
        orbital_period_days: 7.15,
        rotation_period_hours: 171.6,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Jupiter"),
    },
    PlanetConfig {
        name: "Callisto",
        radius_km: 2410.3,
        mass_kg: 1.08e23,
        color: Color::srgb(0.5, 0.5, 0.6),
        orbital_distance_au: 0.0126,
        orbital_period_days: 16.69,
        rotation_period_hours: 400.56,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Jupiter"),
    },
    PlanetConfig {
        name: "Mimas",
        radius_km: 198.2,
        mass_kg: 3.75e19,
        color: Color::srgb(0.8, 0.8, 0.8),
        orbital_distance_au: 0.0012,
        orbital_period_days: 0.94,
        rotation_period_hours: 22.56,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Enceladus",
        radius_km: 252.1,
        mass_kg: 1.08e20,
        color: Color::srgb(0.9, 0.9, 0.9),
        orbital_distance_au: 0.0016,
        orbital_period_days: 1.37,
        rotation_period_hours: 32.88,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Tethys",
        radius_km: 531.1,
        mass_kg: 6.18e20,
        color: Color::srgb(0.7, 0.7, 0.8),
        orbital_distance_au: 0.0020,
        orbital_period_days: 1.89,
        rotation_period_hours: 45.36,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Dione",
        radius_km: 561.4,
        mass_kg: 1.1e21,
        color: Color::srgb(0.7, 0.7, 0.8),
        orbital_distance_au: 0.0025,
        orbital_period_days: 2.74,
        rotation_period_hours: 65.76,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Rhea",
        radius_km: 763.8,
        mass_kg: 2.31e21,
        color: Color::srgb(0.7, 0.7, 0.8),
        orbital_distance_au: 0.0035,
        orbital_period_days: 4.52,
        rotation_period_hours: 108.48,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Titan",
        radius_km: 2574.7,
        mass_kg: 1.35e23,
        color: Color::srgb(0.7, 0.6, 0.4),
        orbital_distance_au: 0.0082,
        orbital_period_days: 15.95,
        rotation_period_hours: 382.8,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Hyperion",
        radius_km: 135.0,
        mass_kg: 5.6e18,
        color: Color::srgb(0.6, 0.5, 0.4),
        orbital_distance_au: 0.0099,
        orbital_period_days: 21.28,
        rotation_period_hours: 510.72,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Iapetus",
        radius_km: 734.5,
        mass_kg: 1.81e21,
        color: Color::srgb(0.8, 0.8, 0.8),
        orbital_distance_au: 0.0238,
        orbital_period_days: 79.32,
        rotation_period_hours: 1903.68,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Saturn"),
    },
    PlanetConfig {
        name: "Miranda",
        radius_km: 235.8,
        mass_kg: 6.41e19,
        color: Color::srgb(0.6, 0.6, 0.7),
        orbital_distance_au: 0.0008,
        orbital_period_days: 1.41,
        rotation_period_hours: 33.84,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Uranus"),
    },
    PlanetConfig {
        name: "Ariel",
        radius_km: 578.9,
        mass_kg: 1.25e21,
        color: Color::srgb(0.7, 0.7, 0.8),
        orbital_distance_au: 0.0012,
        orbital_period_days: 2.52,
        rotation_period_hours: 60.48,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Uranus"),
    },
    PlanetConfig {
        name: "Umbriel",
        radius_km: 584.7,
        mass_kg: 1.28e21,
        color: Color::srgb(0.4, 0.4, 0.5),
        orbital_distance_au: 0.0018,
        orbital_period_days: 4.14,
        rotation_period_hours: 99.36,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Uranus"),
    },
    PlanetConfig {
        name: "Titania",
        radius_km: 788.4,
        mass_kg: 3.53e21,
        color: Color::srgb(0.6, 0.6, 0.7),
        orbital_distance_au: 0.0029,
        orbital_period_days: 8.71,
        rotation_period_hours: 209.04,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Uranus"),
    },
    PlanetConfig {
        name: "Oberon",
        radius_km: 761.4,
        mass_kg: 3.01e21,
        color: Color::srgb(0.5, 0.5, 0.6),
        orbital_distance_au: 0.0039,
        orbital_period_days: 13.46,
        rotation_period_hours: 323.04,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Uranus"),
    },
    PlanetConfig {
        name: "Triton",
        radius_km: 1353.4,
        mass_kg: 2.14e22,
        color: Color::srgb(0.6, 0.7, 0.8),
        orbital_distance_au: 0.0024,
        orbital_period_days: 5.88,
        rotation_period_hours: 141.12,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Neptune"),
    },
    PlanetConfig {
        name: "Proteus",
        radius_km: 210.0,
        mass_kg: 4.4e19,
        color: Color::srgb(0.5, 0.5, 0.6),
        orbital_distance_au: 0.0008,
        orbital_period_days: 1.12,
        rotation_period_hours: 26.88,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Neptune"),
    },
    PlanetConfig {
        name: "Nereid",
        radius_km: 170.0,
        mass_kg: 3.1e19,
        color: Color::srgb(0.6, 0.6, 0.7),
        orbital_distance_au: 0.0369,
        orbital_period_days: 360.13,
        rotation_period_hours: 8643.12,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Neptune"),
    },
    PlanetConfig {
        name: "Larissa",
        radius_km: 97.0,
        mass_kg: 4.2e17,
        color: Color::srgb(0.5, 0.5, 0.5),
        orbital_distance_au: 0.0005,
        orbital_period_days: 0.55,
        rotation_period_hours: 13.2,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Neptune"),
    },
    PlanetConfig {
        name: "Charon",
        radius_km: 603.6,
        mass_kg: 1.59e21,
        color: Color::srgb(0.5, 0.5, 0.5),
        orbital_distance_au: 1.0,
        orbital_period_days: 6.39,
        rotation_period_hours: 153.36,
        axial_tilt_deg: 0.0,
        parent_entity: Some("Pluto"),
    },
];